// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/proto_edn/test.proto

package protoedn.testing;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protoedn.testing.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string login = 2;</code>
     */
    java.lang.String getLogin();
    /**
     * <code>string login = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>int32 age = 3;</code>
     */
    int getAge();

    /**
     * <code>repeated string hobby = 4;</code>
     */
    java.util.List<java.lang.String>
        getHobbyList();
    /**
     * <code>repeated string hobby = 4;</code>
     */
    int getHobbyCount();
    /**
     * <code>repeated string hobby = 4;</code>
     */
    java.lang.String getHobby(int index);
    /**
     * <code>repeated string hobby = 4;</code>
     */
    com.google.protobuf.ByteString
        getHobbyBytes(int index);

    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    int getTagsCount();
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    boolean containsTags(
        java.lang.String key);
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTags();
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTagsMap();
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    java.lang.String getTagsOrThrow(
        java.lang.String key);

    /**
     * <code>.protoedn.testing.User.Sex sex = 6;</code>
     */
    int getSexValue();
    /**
     * <code>.protoedn.testing.User.Sex sex = 6;</code>
     */
    protoedn.testing.Test.User.Sex getSex();

    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    java.util.List<protoedn.testing.Test.User.Child> 
        getChildrenList();
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    protoedn.testing.Test.User.Child getChildren(int index);
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    int getChildrenCount();
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    java.util.List<? extends protoedn.testing.Test.User.ChildOrBuilder> 
        getChildrenOrBuilderList();
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    protoedn.testing.Test.User.ChildOrBuilder getChildrenOrBuilder(
        int index);

    /**
     * <code>bytes avatar = 8;</code>
     */
    com.google.protobuf.ByteString getAvatar();

    public protoedn.testing.Test.User.IdCase getIdCase();
  }
  /**
   * Protobuf type {@code protoedn.testing.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protoedn.testing.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      age_ = 0;
      hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sex_ = 0;
      children_ = java.util.Collections.emptyList();
      avatar_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              idCase_ = 1;
              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              idCase_ = 2;
              id_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hobby_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hobby_.add(s);
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                tags_ = com.google.protobuf.MapField.newMapField(
                    TagsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              tags__ = input.readMessage(
                  TagsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              tags_.getMutableMap().put(
                  tags__.getKey(), tags__.getValue());
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              sex_ = rawValue;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                children_ = new java.util.ArrayList<protoedn.testing.Test.User.Child>();
                mutable_bitField0_ |= 0x00000040;
              }
              children_.add(
                  input.readMessage(protoedn.testing.Test.User.Child.parser(), extensionRegistry));
              break;
            }
            case 66: {

              avatar_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = hobby_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          children_ = java.util.Collections.unmodifiableList(children_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protoedn.testing.Test.internal_static_protoedn_testing_User_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetTags();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protoedn.testing.Test.internal_static_protoedn_testing_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protoedn.testing.Test.User.class, protoedn.testing.Test.User.Builder.class);
    }

    /**
     * Protobuf enum {@code protoedn.testing.User.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>male = 0;</code>
       */
      male(0),
      /**
       * <code>female = 1;</code>
       */
      female(1),
      /**
       * <code>other = 2;</code>
       */
      other(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>male = 0;</code>
       */
      public static final int male_VALUE = 0;
      /**
       * <code>female = 1;</code>
       */
      public static final int female_VALUE = 1;
      /**
       * <code>other = 2;</code>
       */
      public static final int other_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return male;
          case 1: return female;
          case 2: return other;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protoedn.testing.Test.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protoedn.testing.User.Sex)
    }

    public interface ChildOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protoedn.testing.User.Child)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();
    }
    /**
     * Protobuf type {@code protoedn.testing.User.Child}
     */
    public  static final class Child extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protoedn.testing.User.Child)
        ChildOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Child.newBuilder() to construct.
      private Child(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Child() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Child(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoedn.testing.Test.internal_static_protoedn_testing_User_Child_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoedn.testing.Test.internal_static_protoedn_testing_User_Child_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoedn.testing.Test.User.Child.class, protoedn.testing.Test.User.Child.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof protoedn.testing.Test.User.Child)) {
          return super.equals(obj);
        }
        protoedn.testing.Test.User.Child other = (protoedn.testing.Test.User.Child) obj;

        boolean result = true;
        result = result && getName()
            .equals(other.getName());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static protoedn.testing.Test.User.Child parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protoedn.testing.Test.User.Child parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protoedn.testing.Test.User.Child parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protoedn.testing.Test.User.Child parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protoedn.testing.Test.User.Child parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static protoedn.testing.Test.User.Child parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static protoedn.testing.Test.User.Child parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protoedn.testing.Test.User.Child parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static protoedn.testing.Test.User.Child parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static protoedn.testing.Test.User.Child parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static protoedn.testing.Test.User.Child parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static protoedn.testing.Test.User.Child parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(protoedn.testing.Test.User.Child prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protoedn.testing.User.Child}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protoedn.testing.User.Child)
          protoedn.testing.Test.User.ChildOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return protoedn.testing.Test.internal_static_protoedn_testing_User_Child_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return protoedn.testing.Test.internal_static_protoedn_testing_User_Child_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  protoedn.testing.Test.User.Child.class, protoedn.testing.Test.User.Child.Builder.class);
        }

        // Construct using protoedn.testing.Test.User.Child.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return protoedn.testing.Test.internal_static_protoedn_testing_User_Child_descriptor;
        }

        public protoedn.testing.Test.User.Child getDefaultInstanceForType() {
          return protoedn.testing.Test.User.Child.getDefaultInstance();
        }

        public protoedn.testing.Test.User.Child build() {
          protoedn.testing.Test.User.Child result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public protoedn.testing.Test.User.Child buildPartial() {
          protoedn.testing.Test.User.Child result = new protoedn.testing.Test.User.Child(this);
          result.name_ = name_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof protoedn.testing.Test.User.Child) {
            return mergeFrom((protoedn.testing.Test.User.Child)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(protoedn.testing.Test.User.Child other) {
          if (other == protoedn.testing.Test.User.Child.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          protoedn.testing.Test.User.Child parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (protoedn.testing.Test.User.Child) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protoedn.testing.User.Child)
      }

      // @@protoc_insertion_point(class_scope:protoedn.testing.User.Child)
      private static final protoedn.testing.Test.User.Child DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new protoedn.testing.Test.User.Child();
      }

      public static protoedn.testing.Test.User.Child getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Child>
          PARSER = new com.google.protobuf.AbstractParser<Child>() {
        public Child parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Child(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Child> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Child> getParserForType() {
        return PARSER;
      }

      public protoedn.testing.Test.User.Child getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    private int idCase_ = 0;
    private java.lang.Object id_;
    public enum IdCase
        implements com.google.protobuf.Internal.EnumLite {
      NAME(1),
      LOGIN(2),
      ID_NOT_SET(0);
      private final int value;
      private IdCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static IdCase valueOf(int value) {
        return forNumber(value);
      }

      public static IdCase forNumber(int value) {
        switch (value) {
          case 1: return NAME;
          case 2: return LOGIN;
          case 0: return ID_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public IdCase
    getIdCase() {
      return IdCase.forNumber(
          idCase_);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = "";
      if (idCase_ == 1) {
        ref = id_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (idCase_ == 1) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = "";
      if (idCase_ == 1) {
        ref = id_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (idCase_ == 1) {
          id_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOGIN_FIELD_NUMBER = 2;
    /**
     * <code>string login = 2;</code>
     */
    public java.lang.String getLogin() {
      java.lang.Object ref = "";
      if (idCase_ == 2) {
        ref = id_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (idCase_ == 2) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string login = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginBytes() {
      java.lang.Object ref = "";
      if (idCase_ == 2) {
        ref = id_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (idCase_ == 2) {
          id_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int HOBBY_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList hobby_;
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHobbyList() {
      return hobby_;
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public int getHobbyCount() {
      return hobby_.size();
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public java.lang.String getHobby(int index) {
      return hobby_.get(index);
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHobbyBytes(int index) {
      return hobby_.getByteString(index);
    }

    public static final int TAGS_FIELD_NUMBER = 5;
    private static final class TagsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  protoedn.testing.Test.internal_static_protoedn_testing_User_TagsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> tags_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTags() {
      if (tags_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TagsDefaultEntryHolder.defaultEntry);
      }
      return tags_;
    }

    public int getTagsCount() {
      return internalGetTags().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public boolean containsTags(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTags().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTagsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTags() {
      return getTagsMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
      return internalGetTags().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public java.lang.String getTagsOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; tags = 5;</code>
     */

    public java.lang.String getTagsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTags().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int SEX_FIELD_NUMBER = 6;
    private int sex_;
    /**
     * <code>.protoedn.testing.User.Sex sex = 6;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <code>.protoedn.testing.User.Sex sex = 6;</code>
     */
    public protoedn.testing.Test.User.Sex getSex() {
      protoedn.testing.Test.User.Sex result = protoedn.testing.Test.User.Sex.valueOf(sex_);
      return result == null ? protoedn.testing.Test.User.Sex.UNRECOGNIZED : result;
    }

    public static final int CHILDREN_FIELD_NUMBER = 7;
    private java.util.List<protoedn.testing.Test.User.Child> children_;
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    public java.util.List<protoedn.testing.Test.User.Child> getChildrenList() {
      return children_;
    }
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    public java.util.List<? extends protoedn.testing.Test.User.ChildOrBuilder> 
        getChildrenOrBuilderList() {
      return children_;
    }
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    public int getChildrenCount() {
      return children_.size();
    }
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    public protoedn.testing.Test.User.Child getChildren(int index) {
      return children_.get(index);
    }
    /**
     * <code>repeated .protoedn.testing.User.Child children = 7;</code>
     */
    public protoedn.testing.Test.User.ChildOrBuilder getChildrenOrBuilder(
        int index) {
      return children_.get(index);
    }

    public static final int AVATAR_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString avatar_;
    /**
     * <code>bytes avatar = 8;</code>
     */
    public com.google.protobuf.ByteString getAvatar() {
      return avatar_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idCase_ == 1) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (idCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      for (int i = 0; i < hobby_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, hobby_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTags(),
          TagsDefaultEntryHolder.defaultEntry,
          5);
      if (sex_ != protoedn.testing.Test.User.Sex.male.getNumber()) {
        output.writeEnum(6, sex_);
      }
      for (int i = 0; i < children_.size(); i++) {
        output.writeMessage(7, children_.get(i));
      }
      if (!avatar_.isEmpty()) {
        output.writeBytes(8, avatar_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idCase_ == 1) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (idCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hobby_.size(); i++) {
          dataSize += computeStringSizeNoTag(hobby_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHobbyList().size();
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTags().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        tags__ = TagsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, tags__);
      }
      if (sex_ != protoedn.testing.Test.User.Sex.male.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, sex_);
      }
      for (int i = 0; i < children_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, children_.get(i));
      }
      if (!avatar_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, avatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protoedn.testing.Test.User)) {
        return super.equals(obj);
      }
      protoedn.testing.Test.User other = (protoedn.testing.Test.User) obj;

      boolean result = true;
      result = result && (getAge()
          == other.getAge());
      result = result && getHobbyList()
          .equals(other.getHobbyList());
      result = result && internalGetTags().equals(
          other.internalGetTags());
      result = result && sex_ == other.sex_;
      result = result && getChildrenList()
          .equals(other.getChildrenList());
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && getIdCase().equals(
          other.getIdCase());
      if (!result) return false;
      switch (idCase_) {
        case 1:
          result = result && getName()
              .equals(other.getName());
          break;
        case 2:
          result = result && getLogin()
              .equals(other.getLogin());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getHobbyCount() > 0) {
        hash = (37 * hash) + HOBBY_FIELD_NUMBER;
        hash = (53 * hash) + getHobbyList().hashCode();
      }
      if (!internalGetTags().getMap().isEmpty()) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTags().hashCode();
      }
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      if (getChildrenCount() > 0) {
        hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getChildrenList().hashCode();
      }
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      switch (idCase_) {
        case 1:
          hash = (37 * hash) + NAME_FIELD_NUMBER;
          hash = (53 * hash) + getName().hashCode();
          break;
        case 2:
          hash = (37 * hash) + LOGIN_FIELD_NUMBER;
          hash = (53 * hash) + getLogin().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protoedn.testing.Test.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoedn.testing.Test.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoedn.testing.Test.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoedn.testing.Test.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoedn.testing.Test.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protoedn.testing.Test.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protoedn.testing.Test.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoedn.testing.Test.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoedn.testing.Test.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protoedn.testing.Test.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protoedn.testing.Test.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protoedn.testing.Test.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protoedn.testing.Test.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protoedn.testing.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protoedn.testing.User)
        protoedn.testing.Test.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protoedn.testing.Test.internal_static_protoedn_testing_User_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableTags();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protoedn.testing.Test.internal_static_protoedn_testing_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protoedn.testing.Test.User.class, protoedn.testing.Test.User.Builder.class);
      }

      // Construct using protoedn.testing.Test.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getChildrenFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        age_ = 0;

        hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        internalGetMutableTags().clear();
        sex_ = 0;

        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          childrenBuilder_.clear();
        }
        avatar_ = com.google.protobuf.ByteString.EMPTY;

        idCase_ = 0;
        id_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protoedn.testing.Test.internal_static_protoedn_testing_User_descriptor;
      }

      public protoedn.testing.Test.User getDefaultInstanceForType() {
        return protoedn.testing.Test.User.getDefaultInstance();
      }

      public protoedn.testing.Test.User build() {
        protoedn.testing.Test.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protoedn.testing.Test.User buildPartial() {
        protoedn.testing.Test.User result = new protoedn.testing.Test.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (idCase_ == 1) {
          result.id_ = id_;
        }
        if (idCase_ == 2) {
          result.id_ = id_;
        }
        result.age_ = age_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = hobby_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hobby_ = hobby_;
        result.tags_ = internalGetTags();
        result.tags_.makeImmutable();
        result.sex_ = sex_;
        if (childrenBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            children_ = java.util.Collections.unmodifiableList(children_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.children_ = children_;
        } else {
          result.children_ = childrenBuilder_.build();
        }
        result.avatar_ = avatar_;
        result.bitField0_ = to_bitField0_;
        result.idCase_ = idCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protoedn.testing.Test.User) {
          return mergeFrom((protoedn.testing.Test.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protoedn.testing.Test.User other) {
        if (other == protoedn.testing.Test.User.getDefaultInstance()) return this;
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.hobby_.isEmpty()) {
          if (hobby_.isEmpty()) {
            hobby_ = other.hobby_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHobbyIsMutable();
            hobby_.addAll(other.hobby_);
          }
          onChanged();
        }
        internalGetMutableTags().mergeFrom(
            other.internalGetTags());
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        if (childrenBuilder_ == null) {
          if (!other.children_.isEmpty()) {
            if (children_.isEmpty()) {
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureChildrenIsMutable();
              children_.addAll(other.children_);
            }
            onChanged();
          }
        } else {
          if (!other.children_.isEmpty()) {
            if (childrenBuilder_.isEmpty()) {
              childrenBuilder_.dispose();
              childrenBuilder_ = null;
              children_ = other.children_;
              bitField0_ = (bitField0_ & ~0x00000040);
              childrenBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getChildrenFieldBuilder() : null;
            } else {
              childrenBuilder_.addAllMessages(other.children_);
            }
          }
        }
        if (other.getAvatar() != com.google.protobuf.ByteString.EMPTY) {
          setAvatar(other.getAvatar());
        }
        switch (other.getIdCase()) {
          case NAME: {
            idCase_ = 1;
            id_ = other.id_;
            onChanged();
            break;
          }
          case LOGIN: {
            idCase_ = 2;
            id_ = other.id_;
            onChanged();
            break;
          }
          case ID_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protoedn.testing.Test.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protoedn.testing.Test.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int idCase_ = 0;
      private java.lang.Object id_;
      public IdCase
          getIdCase() {
        return IdCase.forNumber(
            idCase_);
      }

      public Builder clearId() {
        idCase_ = 0;
        id_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = "";
        if (idCase_ == 1) {
          ref = id_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (idCase_ == 1) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = "";
        if (idCase_ == 1) {
          ref = id_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (idCase_ == 1) {
            id_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  idCase_ = 1;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        if (idCase_ == 1) {
          idCase_ = 0;
          id_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        idCase_ = 1;
        id_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string login = 2;</code>
       */
      public java.lang.String getLogin() {
        java.lang.Object ref = "";
        if (idCase_ == 2) {
          ref = id_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (idCase_ == 2) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string login = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginBytes() {
        java.lang.Object ref = "";
        if (idCase_ == 2) {
          ref = id_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (idCase_ == 2) {
            id_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string login = 2;</code>
       */
      public Builder setLogin(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  idCase_ = 2;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string login = 2;</code>
       */
      public Builder clearLogin() {
        if (idCase_ == 2) {
          idCase_ = 0;
          id_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string login = 2;</code>
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        idCase_ = 2;
        id_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHobbyIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = new com.google.protobuf.LazyStringArrayList(hobby_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHobbyList() {
        return hobby_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public int getHobbyCount() {
        return hobby_.size();
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public java.lang.String getHobby(int index) {
        return hobby_.get(index);
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHobbyBytes(int index) {
        return hobby_.getByteString(index);
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder setHobby(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addHobby(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addAllHobby(
          java.lang.Iterable<java.lang.String> values) {
        ensureHobbyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hobby_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder clearHobby() {
        hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addHobbyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureHobbyIsMutable();
        hobby_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> tags_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTags() {
        if (tags_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        return tags_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTags() {
        onChanged();;
        if (tags_ == null) {
          tags_ = com.google.protobuf.MapField.newMapField(
              TagsDefaultEntryHolder.defaultEntry);
        }
        if (!tags_.isMutable()) {
          tags_ = tags_.copy();
        }
        return tags_;
      }

      public int getTagsCount() {
        return internalGetTags().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 5;</code>
       */

      public boolean containsTags(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTags().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTagsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTags() {
        return getTagsMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getTagsMap() {
        return internalGetTags().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 5;</code>
       */

      public java.lang.String getTagsOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 5;</code>
       */

      public java.lang.String getTagsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTags().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTags() {
        internalGetMutableTags().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 5;</code>
       */

      public Builder removeTags(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTags().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTags() {
        return internalGetMutableTags().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; tags = 5;</code>
       */
      public Builder putTags(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTags().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; tags = 5;</code>
       */

      public Builder putAllTags(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableTags().getMutableMap()
            .putAll(values);
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>.protoedn.testing.User.Sex sex = 6;</code>
       */
      public int getSexValue() {
        return sex_;
      }
      /**
       * <code>.protoedn.testing.User.Sex sex = 6;</code>
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protoedn.testing.User.Sex sex = 6;</code>
       */
      public protoedn.testing.Test.User.Sex getSex() {
        protoedn.testing.Test.User.Sex result = protoedn.testing.Test.User.Sex.valueOf(sex_);
        return result == null ? protoedn.testing.Test.User.Sex.UNRECOGNIZED : result;
      }
      /**
       * <code>.protoedn.testing.User.Sex sex = 6;</code>
       */
      public Builder setSex(protoedn.testing.Test.User.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protoedn.testing.User.Sex sex = 6;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<protoedn.testing.Test.User.Child> children_ =
        java.util.Collections.emptyList();
      private void ensureChildrenIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          children_ = new java.util.ArrayList<protoedn.testing.Test.User.Child>(children_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoedn.testing.Test.User.Child, protoedn.testing.Test.User.Child.Builder, protoedn.testing.Test.User.ChildOrBuilder> childrenBuilder_;

      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public java.util.List<protoedn.testing.Test.User.Child> getChildrenList() {
        if (childrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(children_);
        } else {
          return childrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public int getChildrenCount() {
        if (childrenBuilder_ == null) {
          return children_.size();
        } else {
          return childrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public protoedn.testing.Test.User.Child getChildren(int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);
        } else {
          return childrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder setChildren(
          int index, protoedn.testing.Test.User.Child value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.set(index, value);
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder setChildren(
          int index, protoedn.testing.Test.User.Child.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.set(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder addChildren(protoedn.testing.Test.User.Child value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder addChildren(
          int index, protoedn.testing.Test.User.Child value) {
        if (childrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureChildrenIsMutable();
          children_.add(index, value);
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder addChildren(
          protoedn.testing.Test.User.Child.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder addChildren(
          int index, protoedn.testing.Test.User.Child.Builder builderForValue) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.add(index, builderForValue.build());
          onChanged();
        } else {
          childrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder addAllChildren(
          java.lang.Iterable<? extends protoedn.testing.Test.User.Child> values) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, children_);
          onChanged();
        } else {
          childrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder clearChildren() {
        if (childrenBuilder_ == null) {
          children_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          childrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public Builder removeChildren(int index) {
        if (childrenBuilder_ == null) {
          ensureChildrenIsMutable();
          children_.remove(index);
          onChanged();
        } else {
          childrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public protoedn.testing.Test.User.Child.Builder getChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public protoedn.testing.Test.User.ChildOrBuilder getChildrenOrBuilder(
          int index) {
        if (childrenBuilder_ == null) {
          return children_.get(index);  } else {
          return childrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public java.util.List<? extends protoedn.testing.Test.User.ChildOrBuilder> 
           getChildrenOrBuilderList() {
        if (childrenBuilder_ != null) {
          return childrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(children_);
        }
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public protoedn.testing.Test.User.Child.Builder addChildrenBuilder() {
        return getChildrenFieldBuilder().addBuilder(
            protoedn.testing.Test.User.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public protoedn.testing.Test.User.Child.Builder addChildrenBuilder(
          int index) {
        return getChildrenFieldBuilder().addBuilder(
            index, protoedn.testing.Test.User.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .protoedn.testing.User.Child children = 7;</code>
       */
      public java.util.List<protoedn.testing.Test.User.Child.Builder> 
           getChildrenBuilderList() {
        return getChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protoedn.testing.Test.User.Child, protoedn.testing.Test.User.Child.Builder, protoedn.testing.Test.User.ChildOrBuilder> 
          getChildrenFieldBuilder() {
        if (childrenBuilder_ == null) {
          childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protoedn.testing.Test.User.Child, protoedn.testing.Test.User.Child.Builder, protoedn.testing.Test.User.ChildOrBuilder>(
                  children_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          children_ = null;
        }
        return childrenBuilder_;
      }

      private com.google.protobuf.ByteString avatar_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes avatar = 8;</code>
       */
      public com.google.protobuf.ByteString getAvatar() {
        return avatar_;
      }
      /**
       * <code>bytes avatar = 8;</code>
       */
      public Builder setAvatar(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes avatar = 8;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protoedn.testing.User)
    }

    // @@protoc_insertion_point(class_scope:protoedn.testing.User)
    private static final protoedn.testing.Test.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protoedn.testing.Test.User();
    }

    public static protoedn.testing.Test.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    public protoedn.testing.Test.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoedn_testing_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoedn_testing_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoedn_testing_User_TagsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoedn_testing_User_TagsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protoedn_testing_User_Child_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protoedn_testing_User_Child_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031test/proto_edn/test.proto\022\020protoedn.te" +
      "sting\"\316\002\n\004User\022\016\n\004name\030\001 \001(\tH\000\022\017\n\005login\030" +
      "\002 \001(\tH\000\022\013\n\003age\030\003 \001(\005\022\r\n\005hobby\030\004 \003(\t\022.\n\004t" +
      "ags\030\005 \003(\0132 .protoedn.testing.User.TagsEn" +
      "try\022\'\n\003sex\030\006 \001(\0162\032.protoedn.testing.User" +
      ".Sex\022.\n\010children\030\007 \003(\0132\034.protoedn.testin" +
      "g.User.Child\022\016\n\006avatar\030\010 \001(\014\032+\n\tTagsEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\032\025\n\005Chi" +
      "ld\022\014\n\004name\030\001 \001(\t\"&\n\003Sex\022\010\n\004male\020\000\022\n\n\006fem" +
      "ale\020\001\022\t\n\005other\020\002B\004\n\002idb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protoedn_testing_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protoedn_testing_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoedn_testing_User_descriptor,
        new java.lang.String[] { "Name", "Login", "Age", "Hobby", "Tags", "Sex", "Children", "Avatar", "Id", });
    internal_static_protoedn_testing_User_TagsEntry_descriptor =
      internal_static_protoedn_testing_User_descriptor.getNestedTypes().get(0);
    internal_static_protoedn_testing_User_TagsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoedn_testing_User_TagsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_protoedn_testing_User_Child_descriptor =
      internal_static_protoedn_testing_User_descriptor.getNestedTypes().get(1);
    internal_static_protoedn_testing_User_Child_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protoedn_testing_User_Child_descriptor,
        new java.lang.String[] { "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
